In [1]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import feature_extraction, linear_model, model_selection, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
fake = pd.read_csv('D:\\6th Sem\\Project- Fake News Detection\\Python Model FN\\Fake.csv',encoding='latin1')
real = pd.read_csv('D:\\6th Sem\\Project- Fake News Detection\\Python Model FN\\True.csv',encoding='latin1')

In [3]:
fake.head(5)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Yearâ...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obamaâs Na...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
real.head(5)

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,31-Dec-17
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,29-Dec-17
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,31-Dec-17
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,30-Dec-17
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,29-Dec-17

In [5]:
fake['target'] = 0
real['target'] = 1

In [6]:
#Combining Title and Text
real["text"] = real["title"] + " " + real["text"]
fake["text"] = fake["title"] + " " + fake["text"]

In [9]:
real["text"]

0        As U.S. budget fight looms, Republicans flip t...
1        U.S. military to accept transgender recruits o...
2        Senior U.S. Republican senator: 'Let Mr. Muell...
3        FBI Russia probe helped by Australian diplomat...
4        Trump wants Postal Service to charge 'much mor...
                               ...
21412    'Fully committed' NATO backs new U.S. approach...
21413    LexisNexis withdrew two products from Chinese ...
21414    Minsk cultural hub becomes haven from authorit...
21415    Vatican upbeat on possibility of Pope Francis ...
21416    Indonesia to buy $1.14 billion worth of Russia...
Name: text, Length: 21417, dtype: object

In [10]:
real = real.drop(["subject", "date","title"], axis=1)
fake = fake.drop(["subject", "date", "title"], axis=1)

In [11]:
real

                                                    text  target
0      As U.S. budget fight looms, Republicans flip t...       1
1      U.S. military to accept transgender recruits o...       1
2      Senior U.S. Republican senator: 'Let Mr. Muell...       1
3      FBI Russia probe helped by Australian diplomat...       1
4      Trump wants Postal Service to charge 'much mor...       1
...                                                  ...     ...
21412  'Fully committed' NATO backs new U.S. approach...       1
21413  LexisNexis withdrew two products from Chinese ...       1
21414  Minsk cultural hub becomes haven from authorit...       1
21415  Vatican upbeat on possibility of Pope Francis ...       1
21416  Indonesia to buy $1.14 billion worth of Russia...       1

[21417 rows x 2 columns]

In [12]:
data = real.append(fake, ignore_index=True)
del real, fake

In [13]:
data

                                                    text  target
0      As U.S. budget fight looms, Republicans flip t...       1
1      U.S. military to accept transgender recruits o...       1
2      Senior U.S. Republican senator: 'Let Mr. Muell...       1
3      FBI Russia probe helped by Australian diplomat...       1
4      Trump wants Postal Service to charge 'much mor...       1
...                                                  ...     ...
44893  McPain: John McCain Furious That Iran Treated ...       0
44894  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...       0
44895  Sunnistan: US and Allied âSafe Zoneâ Plan ...       0
44896  How to Blow $700 Million: Al Jazeera America F...       0
44897  10 U.S. Navy Sailors Held by Iranian Military ...       0

[44898 rows x 2 columns]

In [14]:
from sklearn.utils import shuffle
data = shuffle(data)
data = data.reset_index(drop=True)
data.head()

                                                text  target
0  Trump supporters tricked into buying beers at ...       1
1  Tillerson, Lavrov agree to continue North Kore...       1
2  Bernie Sanders brings local politics focus to ...       1
3  GERMANY: 10,000 Muslims Allegedly Registered T...       0
4  TUCKER CARLSON Demolishes Business Owner Who W...       0

In [16]:
data.isnull().any()

text      False
target    False
dtype: bool

In [17]:
data['text'] = data['text'].apply(lambda x: x.lower())
data

                                                    text  target
0      trump supporters tricked into buying beers at ...       1
1      tillerson, lavrov agree to continue north kore...       1
2      bernie sanders brings local politics focus to ...       1
3      germany: 10,000 muslims allegedly registered t...       0
4      tucker carlson demolishes business owner who w...       0
...                                                  ...     ...
44893  senate intelligence committee leaders confirm ...       1
44894  white house deregulation push clears out hundr...       1
44895   breaking: yet another trump advisor caught wi...       0
44896  factbox: trump fills top jobs for his administ...       1
44897  âpresident trump fights fire with fireâ sa...       0

[44898 rows x 2 columns]

In [18]:
import string
def punctuation_removal(text):
    all_list = [char for char in text if char not in string.punctuation]
    clean_str = ''.join(all_list)
    return clean_str
data['text'] = data['text'].apply(punctuation_removal)
data

                                                    text  target
0      trump supporters tricked into buying beers at ...       1
1      tillerson lavrov agree to continue north korea...       1
2      bernie sanders brings local politics focus to ...       1
3      germany 10000 muslims allegedly registered to ...       0
4      tucker carlson demolishes business owner who w...       0
...                                                  ...     ...
44893  senate intelligence committee leaders confirm ...       1
44894  white house deregulation push clears out hundr...       1
44895   breaking yet another trump advisor caught wit...       0
44896  factbox trump fills top jobs for his administr...       1
44897  âpresident trump fights fire with fireâ sa...       0

[44898 rows x 2 columns]

In [19]:
#stopwords removal
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')
data['text'] = data['text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
data.head(50)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HZT\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

                                                 text  target
0   trump supporters tricked buying beers mexico c...       1
1   tillerson lavrov agree continue north korea di...       1
2   bernie sanders brings local politics focus mas...       1
3   germany 10000 muslims allegedly registered â...       0
4   tucker carlson demolishes business owner wonâ...       0
5   greek government spat spains ambassador catalo...       1
6   japans abe says un resolution must force chang...       1
7   trump picks giuliani assemble cyber security m...       1
8   us government watchdog calls changes afghan tr...       1
9   house intelligence panel leaders split session...       1
10  meeting military trump talks calm storm washin...       1
11  âracistâ president jackson replaced black ...       0
12  fox news fires one longest running hosts heâ...       0
13  trump considering palin lead veterans affairs ...       1
14  new york gun license broker paid cops approve ...       0
15  breaking nyc bombing suspect arrested shooting...       0
16  harsh true top ten reasons obama worst preside...       0
17  busted antitrump protesters paid stir violence...       0
18  nancy pelosi confused time âis afternoonâ ...       0
19  two days ago trump asked russia hack clinton t...       0
20  detective seth rich murder mystery drops shock...       0
21  muslim scholar criticizes obamaâ¦explains ame...       0
22  election crisis engulfs honduras rivals neckan...       1
23  contenders senior jobs trumps administration r...       1
24  usas tillerson saudi crown prince discuss terr...       1
25  trump started war mcconnell oldest gop senator...       0
26  arab states urge us abandon jerusalem move sta...       1
27  cnn asks brutal child rape case affect hillary...       0
28  latest gun control bid falters congress democr...       1
29  wife vanished british lord heart murder myster...       1
30  refugee crisis influx boon german integration ...       1
31  trumps big announcement tax broad principles o...       1
32  fbi deputy director sit closed interview house...       1
33  trump says feud senator corker hurt tax push w...       1
34  election congress pivots lameduck debate spend...       1
35  syrias assad calls usbacked militias traitors ...       1
36  trump uncomfortable moment merkel makes fool v...       0
37  trump tightens grip us republican nomination n...       1
38  nyc mayor deblasio says âsomething changing ...       0
39  eu mediate catalan crisis frances macron frank...       1
40  hillary makes first appearance since electionâ...       0
41  one last time dime mooch barack arrive marthaâ...       0
42  obama blames russia hillaryâs loss new harva...       0
43  cnnâs lemon alcoholic drunk day day cnn work...       0
44  white nationalist radio trump gave us press pa...       0
45  zionist billionaire give 100 million trump cam...       0
46  breaking kansas city police captain shot dead ...       0
47  charity gets millions us train âvulnerable a...       0
48  watch florida gov rick scott disrespects presi...       0
49  kushner cos says skip china marketing push wee...       1

In [26]:
import gensim

In [27]:
nltk.download('punkt')
X = []
stop_words = set(nltk.corpus.stopwords.words("english"))
tokenizer = nltk.tokenize.RegexpTokenizer(r'\w+')
for par in data["text"].values:
    tmp = []
    sentences = nltk.sent_tokenize(par)
    for sent in sentences:
        sent = sent.lower()
        tokens = tokenizer.tokenize(sent)
        filtered_words = [w.strip() for w in tokens if w not in stop_words and len(w) > 1]
        tmp.extend(filtered_words)
    X.append(tmp)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HZT\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

In [ ]:
EMBEDDING_DIM = 100

#Creating Word Vectors by Word2Vec Method (takes time...)
w2v_model = gensim.models.Word2Vec(sentences=X, size=EMBEDDING_DIM, window=5, min_count=1)

In [ ]:
w2v_model.wv.most_similar("iran")